Beacocleaning
RotaruDan/test-users pull request #111
Opened 2018-09-18 14:58 UTC by Synpheros

2018-09-19 13:20 UTC, gorco reviewed
Please, remove the package-lock.json from the repository

2018-09-19 15:28 UTC, gorco commented
Done, please, check the commets. In general, nice pr

2018-09-24 10:40 UTC, gorco requested changes

2018-09-24 10:40 UTC, gorco commented on loginPlugins/beaconing.js
> +var callback = 'https://localhost:3000/api/proxy/afront/loginbyplugin';
I think that callback, pluginId, pluginId and passport object fields should be load from a config file.

2018-09-24 10:40 UTC, gorco commented on loginPlugins/beaconing.js
> +        return profile.id + profile.username  + '@beaconing.eu';
What happen if the email already exist?

2018-09-24 10:40 UTC, gorco commented on loginPlugins/beaconing.js
> +                err = new Error('No account with that email address exists.');
You search a user by "username" but error say "no email address exists" and, also, should indicates what account doesn't exist.

2018-09-24 10:40 UTC, gorco commented on loginPlugins/beaconing.js
> +        db.model('user').findOne({username: profile.username}, function (err, user) {
Also, the username is unique, so you can use `find()` instead of `findOne()`.

2018-09-24 10:40 UTC, gorco commented on loginPlugins/beaconing.js
> +            var userRoles = function(){
If the user exist you should return an error. Imagine that the user already exist, these user maybe is not the same that the new user that you are registering.

2018-09-24 10:40 UTC, gorco commented on routes/users.js
> + * @api {get} /users/:domain/:externalId Gets the user information using externalId
maybe the route should be `/users/domain/:domain/id/:externalId`

2018-09-24 10:40 UTC, gorco commented on routes/users.js
> +    if(!domain){
if domain or externalId not exist this get call doesn't happen. So you don't have to check it. You should check if domain and externalId are valid, but not if exist

2018-09-24 10:40 UTC, gorco commented on routes/users.js
> + * @api {get} /users/external/:domain/:externalId Gets the user information using externalId
This commit modifies code from the previous commit, please merge both. And I comment this line on previous commit. With "external" is better than before url

2018-09-24 10:40 UTC, gorco commented on routes/users.js
> +    if (!domain) {
same that before (domain and expertalId exist always)

2018-09-24 10:40 UTC, gorco commented on routes/applications.js
> +        if (req.body.users) {
is a new field? please, update doc

2018-09-24 11:22 UTC, Synpheros commented on loginPlugins/beaconing.js
> +var callback = 'https://localhost:3000/api/proxy/afront/loginbyplugin';
This is the default callback url. It is configurable as a query parameter in GET /login/beaconing?callback=$url

2018-09-24 16:05 UTC, Synpheros commented on loginPlugins/beaconing.js
> +                err = new Error('No account with that email address exists.');
This was corrected in a future commit

2018-09-24 16:34 UTC, Synpheros commented on loginPlugins/beaconing.js
> +            var userRoles = function(){
I've made it configurable with a flag. By default it'll return an error!
Nice catch

2018-09-25 10:46 UTC, Synpheros commented on loginPlugins/beaconing.js
> +        db.model('user').findOne({username: profile.username}, function (err, user) {
Stays like this as discussed in A16

2018-10-01 14:12 UTC, Synpheros commented on routes/users.js
> + * @api {get} /users/:domain/:externalId Gets the user information using externalId
solved

2018-10-01 14:12 UTC, Synpheros commented on routes/users.js
> +    if(!domain){
solved

2018-10-01 14:12 UTC, Synpheros commented on routes/users.js
> + * @api {get} /users/external/:domain/:externalId Gets the user information using externalId
solved

2018-10-01 14:13 UTC, Synpheros commented on routes/users.js
> +    if (!domain) {
solved

2018-10-02 19:13 UTC, Synpheros commented
Dear @gorco, all the changes have been added and tested!. I think it's ready to be merged 👍

2018-10-03 08:55 UTC, gorco commented
Great, but I think there are two that have not been solved, please check the following comments:
"is a new field? please, update doc" (in /users.js)
"if domain or externalId not exist this get call doesn't happen. So you don't have to check it. You should check if domain and externalId are valid, but not if exist" (in /users.js)

2018-10-03 10:42 UTC, merged